#!/usr/bin/env bash

set -E
trap 'echo Failed on line: $LINENO at command: $BASH_COMMAND && exit $?' ERR

if [ -z $LOCAL ]; then
  sudo -i /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  brew install mc
fi

basedir="$(pwd)"
# Take a build of midnight commander made with brew and make it relocatable
target="$(pwd)/target"
rm -rf ${target} > /dev/null 2>&1
brewMc="/usr/local/Cellar/midnight-commander/4.8.27"
mkdir -p ${target}
cp -r ${brewMc}/* ${target}

SRC="${target}/bin/mc"
LIB="${target}/lib/"
mkdir -p $LIB

# Make the library paths relative to the binary
EXEC=@executable_path/../lib/

# This assumes that all the required libraries are installed. So using brew here
# to get the necessary libraries is useful.
CPL="/usr/local/lib/"
CPL2="/usr/local/opt/"

get_dylibs() {
  echo $(otool -L $1 | grep -E "/opt.*dylib[^:]" | awk -F' ' '{ print $1 }')
}

fix_dylib() {
  DYLIBS=$(get_dylibs $1)
  for dylib in $DYLIBS; do
    #echo "> ${dylib}"

    lib="$CPL$(basename $dylib)"
    if [ ! -f ${lib} ]; then
      lib="$CPL2$(basename $dylib)"
    fi

    if [ -f ${lib} ]; then
      cp -f ${lib} $LIB
      chmod 755 ${lib}
      echo "install_name_tool -change $dylib $EXEC$(basename $dylib) $1"
      install_name_tool -change $dylib $EXEC$(basename $dylib) $1
    fi

    DYLIBS2=$(get_dylibs $dylib)
    for dylib2 in $DYLIBS2; do
      #echo ">> ${dylib2}"
      lib2="$dylib2"
      cp -f ${lib2} $LIB
      chmod 755 $LIB$(basename $dylib2)
      echo "install_name_tool -change $dylib2 $EXEC$(basename $dylib2) $LIB$(basename $dylib)"
      install_name_tool -change $dylib2 $EXEC$(basename $dylib2) $LIB$(basename $dylib)

      DYLIBS3=$(get_dylibs $LIB$(basename $dylib2))
      for dylib3 in $DYLIBS3; do
        #echo ">>> ${dylib3}"
        lib3="$dylib3"
        cp -f ${lib3} $LIB
        chmod 755 $LIB$(basename $dylib3)
        echo "install_name_tool -change $dylib3 $EXEC$(basename $dylib3) $LIB$(basename $dylib2)"
        install_name_tool -change $dylib3 $EXEC$(basename $dylib3) $LIB$(basename $dylib2)
      done
    done
  done

  #install_name_tool -change /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib @executable_path/../lib/libssl.1.1.dylib /Users/jvanzyl/js/provisio/provisio-repackage/mc/target/lib/libssl.1.1.dylib
  install_name_tool \
    -change /usr/local/Cellar/openssl@1.1/1.1.1m/lib/libcrypto.1.1.dylib \
    @executable_path/../lib/libcrypto.1.1.dylib \
    ${target}/lib/libssl.1.1.dylib

  for dylib in $LIB*; do
    echo "install_name_tool -id $(basename $dylib) $dylib"
    install_name_tool -id $(basename $dylib) $dylib
  done

}

fix_dylib $SRC 1

cd "${target}/bin"
ln -sf mc mcdiff
ln -sf mc mcedit
ln -sf mc mcview
cd -

mkdir -p ${basedir}/repackage
cd ${target}
tar -cvzf ${basedir}/repackage/mc-Darwin-x86_64-4.8.27.tar.gz *
